package net.perfectdreams.discordinteraktions.common.components.buttons

import net.perfectdreams.discordinteraktions.common.components.ComponentExecutor

interface ButtonClickExecutor : ComponentExecutor