package net.perfectdreams.discordinteraktions.common.components.selects

import net.perfectdreams.discordinteraktions.common.components.ComponentExecutor

interface SelectMenuExecutor : ComponentExecutor